<?php

namespace App\Models\Admin;

use App\Models\Scopes\Searchable;
use Illuminate\Database\Eloquent\Model;
use Illuminate\Database\Eloquent\Factories\HasFactory;

class SkillSubCategory extends Model
{
    use HasFactory;
    use Searchable;

    protected $fillable = [
        'skill_category_id',
        'sub_category_name',
        'slug',
        'status',
    ];

    protected $searchableFields = ['*'];

    protected $table = 'skill_sub_categories';

    private static $skillSubCategory;

    public static function boot()
    {
        parent::boot(); // TODO: Change the autogenerated stub
        static::deleting(function ($skillSubCategory){
            if (!empty($skillSubCategory->skills))
            {
                $skillSubCategory->skills->each->delete();
            }
        });
    }

    public static function createOrUpdateSkillSubCategory ($request, $id = null)
    {
        SkillSubCategory::updateOrCreate(['id' => $id], [
            'skill_category_id'     => $request->skill_category_id,
            'sub_category_name'     => $request->sub_category_name,
            'slug'                  => str_replace(' ', '-', $request->sub_category_name),
            'status'                => $request->status == 'on' ? 1 : 0,
        ]);
    }

    public function skillCategory()
    {
        return $this->belongsTo(SkillCategory::class);
    }

    public function skills()
    {
        return $this->hasMany(Skill::class);
    }

//    public function jobPosts()
//    {
//        return $this->hasMany(JobPost::class);
//    }
}
