<?php

namespace App\Models\Admin;

use App\Models\Scopes\Searchable;
use Illuminate\Database\Eloquent\Model;
use Illuminate\Database\Eloquent\Factories\HasFactory;

class SkillCategory extends Model
{
    use HasFactory;
    use Searchable;

    protected $fillable = ['category_name', 'slug', 'status'];

    protected $searchableFields = ['*'];

    protected $table = 'skill_categories';

    private static $skillCategory;

    public static function boot()
    {
        parent::boot(); // TODO: Change the autogenerated stub
        static::deleting(function ($skillCategory){
            if (!empty($skillCategory->skillSubCategory))
            {
                $skillCategory->skillSubCategory->each->delete();
            }
        });
    }

    public static function createOrUpdateSkillCategory ($request, $id = null)
    {
        SkillCategory::updateOrCreate(['id' => $id], [
            'category_name'     => $request->category_name,
            'slug'              => str_replace(' ', '-', $request->category_name),
            'status'            => $request->status == 'on' ? 1 : 0,
        ]);
    }

    public function skillSubCategories()
    {
        return $this->hasMany(SkillSubCategory::class);
    }

    public function skills()
    {
        return $this->hasMany(Skill::class);
    }

//    public function jobPosts()
//    {
//        return $this->hasMany(JobPost::class);
//    }
}
